language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew test buildPlugin --console=plain

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

deploy:
  provider: script
  script: ./gradlew clean test publishPlugin --console=plain
  on:
    tags: true
    all_branches: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
